# Generated by Django 4.2.2 on 2023-06-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('skills', models.CharField(max_length=200)),
                ('tools', models.CharField(max_length=200)),
            ],
        ),
    ]
